### ISSUE TITLE
rpc blockchain.relayfee peer panicked on 'Option::unwrap()'

### ISSUE THREAD

**Issue by Zaytion** [shesek/bwt#113]
version: bwt-electrum-plugin-0.2.4-x86_64-linux.tar.gz 

Console:
INFO bwt::electrum » [127.0.0.1:37314] connected peer
DEBUG bwt::electrum » rpc #0 <- server.version ["electrum/4.3.4","1.4"]
DEBUG bwt::electrum » rpc #1 <- blockchain.headers.subscribe null
DEBUG bwt::electrum » rpc #6 <- server.banner null
DEBUG bwt::electrum » rpc #7 <- server.donation_address null
DEBUG bwt::electrum » rpc #8 <- server.peers.subscribe null
DEBUG bwt::electrum » rpc #9 <- blockchain.relayfee null
INFO bwt » thread 'peer' panicked at 'called `Option::unwrap()` on a `None` value', src/util/mod.rs:33:45

**Comment by shesek** [comment]
Hi! Thanks for the report. This is due to an incompatibility with Bitcoin Core v23.0, which was already fixed on master by #97 but still not officially released in the latest v0.2.4. It should work with the next release.
