### ISSUE TITLE
invalid value: integer `-1`, expected usize

### ISSUE THREAD

**Issue by yoss1x** [shesek/bwt#17]
Ubuntu 19.10, Core v0.19.1, see [electrum.log](https://github.com/shesek/bwt/files/4687502/electrum.log)

**Comment by shesek** [comment]
This happens due to this: https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/110

Will shortly release a fix as part of v0.1.1.

**Comment by shesek** [comment]
Fixed by https://github.com/shesek/bwt/commit/1afaddea97e6932081d59becb9199414b16697cf, released in v0.1.1.
