### ISSUE TITLE
ARM builds

### ISSUE THREAD

**Issue by shesek** [shesek/bwt#19]

**Comment by dr-bonez** [comment]
Happy to take this on if no one is already on it.

**Comment by dr-bonez** [comment]
I have successfully cross-compiled to armv7-unknown-linux-musleabihf using https://github.com/Start9Labs/rust-musl-cross. No modifications were necessary.

**Comment by dr-bonez** [comment]
I have successfully cross-compiled to armv7-unknown-linux-gnueabihf using https://github.com/Start9Labs/rust-arm-builder. No modifications were necessary.

**Comment by shesek** [comment]
> I have successfully cross-compiled to armv7-unknown-linux-gnueabihf using https://github.com/Start9Labs/rust-arm-builder. No modifications were necessary.

Very nice!

I'm not very experienced with Rust cross-compilation, but is the docker image necessary to make this work? I'm able to cross compile Windows builds from my Linux by just using the right target, and some online resources suggest that it should be possible for arm as well.

If it is necessary, could https://github.com/rust-embedded/cross be suitable to do this?

**Comment by dr-bonez** [comment]
docker is not strictly necessary for cross compilation, you can always setup the full necessary environment locally. However, most projects rely on a gcc cross-compiler and openssl for the desired target. These docker images already have that set up, so it is a lot more convenient. I have not used `cross` before but I imagine it works fairly similarly to the above images.

**Comment by dr-bonez** [comment]
looks like `cross` works out of box as well
