### ISSUE TITLE
Electrum Plugin RPC Error

### ISSUE THREAD

**Issue by afhacker** [shesek/bwt#22]
I got this error when I tried to connect to my Bitcoin Node on plugin log box:

ERROR bwt » JSON-RPC error: RPC error response: RpcError { code: -13, message: "Error: Please enter the wallet passphrase with walletpassphrase first.", data: None }

I have only one wallet on my Bitcoin core which was imported by Electrum Personal Server, I left the wallet textbox blank.

My Bitcoin core is 0.19.1 and Electrum 3.3.8.

**Comment by shesek** [comment]
Create a separate bitcoind wallet for bwt. You should not use the same wallet as what EPS uses.

See: https://github.com/shesek/bwt#bitcoin-core-multi-wallet
