### ISSUE TITLE
Bitcoind pruned mode?

### ISSUE THREAD

**Issue by leshik** [shesek/bwt#26]
Does it support `bitcoind` pruned mode, as `eps` does? In particular the Electrum plugin?

**Comment by shesek** [comment]
Pruning kind of works, you won't have any history that happened before importing the addresses (not even from blocks that didn't get pruned yet, bitcoind doesn't support rescanning in prune mode at all), so really only usable if you just created a brand new wallet. Once the addresses are imported, the transactions should be kept around by bitcoind regardless of pruning. This is similar to how EPS works with pruning.

You'll need to set the rescan time to `none` with `--xpub <xpub>:none` to tell bwt to not attempt rescanning.

In a future release, showing some partial history (only of transactions that still have unspent outputs) could be possible with `scantxoutset`. See this ticket on the EPS tracker for more details:

https://github.com/chris-belcher/electrum-personal-server/issues/27

**Comment by shesek** [comment]
Closing this in favor of #27, which I opened for tracking `scantxoutset` support.
