### ISSUE TITLE
invalid request from Eclair mobile app

### ISSUE THREAD

**Issue by azagato** [shesek/bwt#28]
I get this using with Eclair mobile app:

INFO  bwt::electrum > [192.168.1.148:39430] connected peer
 ERROR bwt::electrum > [192.168.1.148:39430] receiver failed: invalid request - maybe SSL-encrypted data?: [22, 3, 1, 0, 218, 1, 0, 0, 214, 3, 3, 141, 209, 205, 69, 67, 214, 195, 169, 204, 56, 252, 162, 84, 8, 37, 254, 214, 151, 104, 234, 116, 137, 158, 222, 68, 102, 229, 54, 104, 189, 206, 166, 32, 173, 223, 108, 58, 249, 196, 20, 103, 78, 187, 180, 252, 172, 199, 164, 57, 199, 61, 153, 146, 47, 11, 112, 245, 24, 215, 128, 150, 228, 249, 100, 32, 0, 24, 19, 1, 19, 2, 19, 3, 192, 44, 192, 43, 192, 47, 192, 48, 192, 19, 192, 20, 0, 156, 0, 47, 0, 53, 1, 0, 0, 117, 0, 23, 0, 0, 255, 1, 0, 1, 0, 0, 10]
 INFO  bwt::electrum > [192.168.1.148:39430] disconnected peer

**Comment by shesek** [comment]
It appears like you'll have to setup SSL for Eclair mobile. bwt does not support this out of the box, you will have to setup a reverse proxy with SSL using something like nginx.

See the instructions here, which should work as-is for bwt (they were written for electrs): https://github.com/romanz/electrs/blob/master/doc/usage.md#extra-configuration-suggestions

Also see: https://github.com/romanz/electrs/pull/126

**Comment by shesek** [comment]
I created [an issue](#29) for adding an easier way to setup ssl. I'm closing this now, but please do report back if you try following the nginx ssl instructions and still having issues.
