### ISSUE TITLE
BWT plugin not showing on electrum

### ISSUE THREAD

**Issue by Dwyte** [shesek/bwt#30]
I already pasted the bwt file from the compressed file on the directory said, I wasn't sure if it is `/electrum/plugins` like the root dir or `~/.electrum/plugins` home dir one, both seems doesnt work atleast on my end, maybe I am missing something thanks!

I am using a standalone executable electrum 3.3.8

**Comment by shesek** [comment]
You cannot install external plugins with the standalone executable. See [here](https://github.com/shesek/bwt#electrum-plugin):

> Note that it is not possible to install external plugins with the Electrum AppImage or standalone Windows executable. You will need to [run from tar.gz](https://github.com/spesmilo/electrum/#running-from-targz) on Linux, use the Windows installer, or [run from source](https://github.com/spesmilo/electrum/#development-version-git-clone).

**Comment by Dwyte** [comment]
oops, okie, sorry my bad didn't recognized that
