### ISSUE TITLE
Support for multisig

### ISSUE THREAD

**Issue by junderw** [shesek/bwt#31]
Support for tracking multisig wallets.

Types:
- m-of-n p2sh + sort pubkeys for each script
- m-of-n p2sh-p2wsh + sort pubkeys for each script
- m-of-n p2wsh + sort pubkeys for each script
- m-of-n p2sh + do not sort pubkeys for each script
- m-of-n p2sh-p2wsh + do not sort pubkeys for each script
- m-of-n p2wsh + do not sort pubkeys for each script

The "xpub" format could be extended in a similar way to NBXplorer (the wallet backend for BTCPay).

https://github.com/dgarage/NBXplorer/blob/8715d3d1ba2a519bd67678ed4be050487f2c9994/docs/API.md#derivationScheme

**Comment by shesek** [comment]
Support for multisig will be added as part of the more generalized support for [script descriptors](https://github.com/shesek/bwt/issues/1). I'm closing this ticket in favor of tracking there.

**Comment by shesek** [comment]
I have a branch with descriptor support: https://github.com/shesek/bwt/commits/202010-descriptor

This will soon be released in bwt v0.1.6 (or maybe v0.2.0). But note that rust-miniscript does not yet support `sortedmulti()`, so it'll initially only support your last 3 types. I understand that `sortedmulti()` is expected to land in rust-miniscript though.
