### ISSUE TITLE
Waiting IBD completion on regtest is too long.

### ISSUE THREAD

**Issue by kannapoix** [shesek/bwt#35]
bwt is waiting for completion of bitcoind's IBD(initial block download).  
Connecting to bitcoind running regtestmode, this could be take long time.  
I know bwt is not responsible for this. But I just want to know how can I avoid this.  
Maybe I should ask how can I make finish IBD mode on regtest to bitcoin core community.

**Comment by shesek** [comment]
Regtest goes into IBD mode when there are no new blocks for awhile, it should work if you generate a new block (with i.e. `bitcoin-cli -regtest generatetoaddress 1 $(bitcoin-cli -regtest getnewaddress)`).

There's also an [handy script for setting up a dev environment](https://github.com/shesek/bwt#development-environment) that you could try using.

**Comment by shesek** [comment]
Closing for now, please report back if you're still having issues.
