### ISSUE TITLE
Error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by maltokyo** [shesek/bwt#41]
When running:
`docker-compose up --remove-orphans` I get the following error:
```
Recreating docker-bwt-shesek_bwt_1 ... done
Attaching to docker-bwt-shesek_bwt_1
bwt_1  | bwt: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
docker-bwt-shesek_bwt_1 exited with code 127
```

Would it be possible that anyone has a good docker-compose.yml file I could use as a starting point?

**Comment by shesek** [comment]
What docker compose file are you using?

**Comment by shesek** [comment]
You need to have `libssl-dev` installed, but that should already be the case if you're using the `Dockerfile` published here.

**Comment by shesek** [comment]
Closing this for now, please report back with more information.
