### ISSUE TITLE
Plugin, No hot wallet policy also applies to Hardware wallet

### ISSUE THREAD

**Issue by Transisto** [shesek/bwt#47]
![image](https://user-images.githubusercontent.com/388716/86500269-e7fdce80-bd5d-11ea-8962-573b22e061de.png)

**Comment by Transisto** [comment]
This is seriously limiting the usefulness if it can't be used to transact in the same app.

**Comment by shesek** [comment]
Hi, sorry for the slow reply, looks like I somehow missed that between all the notifications!

I'm investigating, should hopefully have a fix ready soon.

**Comment by shesek** [comment]
I believe 9b68cc9844cd260c37c4dd07f09a500ff93460c0 should fix this, but can't currently test it to verify. Can you try and see if that works for you?

You can do this by downloading [`bwt.py`](https://github.com/shesek/bwt/raw/master/contrib/electrum-plugin/bwt.py) into your plugin directory (overwriting the previous one) and restarting Electrum.

**Comment by Transisto** [comment]
Thanks will try this out

**Comment by Hieroni** [comment]
This fix does not work with Electrum 4.0.2, right?
Does it work with Electrum 3.x.x?

**Comment by shesek** [comment]
@Hieroni The plugin currently supports Electrum v3 only, I'll hopefully have a v4-compatible release ready soon (though initially without lightning support, which adds some compilations and might potentially require changes on the electrum side).

**Comment by shesek** [comment]
@Hieroni Note that if you setup the standalone server instead of using the plugin, this will work with Electrum 4, with the exception of not supporting lightning.

**Comment by shesek** [comment]
A fix for this was released in v0.1.5. This release also made the plugin compatibile with Electrum v4 (minus lightning).

@Hieroni @Transisto
